# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/android:api-23-alpha

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m

    branches:
      only:
        - master
        - develop
        - /sprint-.*/

    steps:
      # This will allow us to avoid unkown hosts error
      - run:
          name: Avoid hosts unknown for github
          command: mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config

      - run:
          name: Checkout android-dtn-foundation
          command: git clone -b $CIRCLE_BRANCH git@github.com:dinnertonight/android-dtn-foundation.git ~/android-dtn-foundation

      - checkout

      # Download and cache dependencies
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "DinnerTonight/build.gradle" }}

      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies

      - save_cache:
          paths:
           - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "DinnerTonight/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_artifacts:
          path: DinnerTonight/build/reports
          destination: reports
      - store_test_results:
          path: DinnerTonight/build/test-results

